### ISSUE TITLE
Google Font module not working in Safari on Nuxt

### ISSUE THREAD

**Issue by pixelyze** [nuxt-modules/google-fonts#128]
The module fails to load in Safari. Any solution?

**Comment by ricardogobbosouza** [comment]
Hi @pixelyze 
Could you tell me what doesn't work in Safari?

**Comment by ricardogobbosouza** [comment]
![Captura de Tela 2023-07-21 às 15 55 36](https://github.com/nuxt-modules/google-fonts/assets/13064722/66a1e529-3d1c-4425-b4e0-66c1c017f532)

**Comment by WiIIiam278** [comment]
Can confirm this is still an issue and has been from the beginning (have been upgrading versions of this in hope this will eventually get released) -- this module simply fails to work entirely on Safari for both iOS and macOS with my setup, and fonts on my site just use their fallback fonts.

Running google-fonts@v3.0.2. Works perfectly on desktop chrome.

My `nuxt.config.js`:
```js
googleFonts: {
        download: true,
        inject: true,
        families: {
            'Nunito': [400, 700],
            'JetBrains Mono': [400, 700]
        }
    },
```

site code (always possible it's something I'm doing wrong?) https://github.com/WiIIiam278/william278-site (hosted ver: https://william278.net) -- tested running this on my mac with both npm run dev and building statically and hosting. No errors in console or errors fetching resources in the network tab, it simply silently fails to use the fonts for me \:(

Thanks for your work :)

**Comment by ricardogobbosouza** [comment]
Hi @WiIIiam278 
Apparently the module will never run, you are using `buildModules`, move must use `modules`
https://github.com/WiIIiam278/william278-site/blob/master/nuxt.config.js#L4-L5

See https://nuxt.com/docs/migration/configuration#migration-1

**Comment by WiIIiam278** [comment]
> Hi @WiIIiam278 Apparently the module will never run, you are using `buildModules`, move must use `modules` https://github.com/WiIIiam278/william278-site/blob/master/nuxt.config.js#L4-L5
> 
> See https://nuxt.com/docs/migration/configuration#migration-1

Ahh, gotcha, gotcha. Got tangled up during migration along while back :)
Many thanks for your reply! Working now.
