### ISSUE TITLE
Deprecated info on the docs

### ISSUE THREAD

**Issue by devberkay** [nuxt-modules/google-fonts#132]
<img width="1049" alt="Screenshot 2023-04-22 at 4 03 08 PM" src="https://user-images.githubusercontent.com/81699676/233786480-215e162a-c086-4e8a-b204-ab141752dad9.png">

Nuxt 3 docs says nuxt modules are now build-time only and  `buildModules` property is deprecated in favor of `modules`

<img width="518" alt="Screenshot 2023-04-22 at 4 07 14 PM" src="https://user-images.githubusercontent.com/81699676/233786988-0ffc9608-acca-479d-ad43-52f0881b1bc0.png">

[nuxt/google-fonts docs](https://google-fonts.nuxtjs.org/) says  Nuxt < v2.9 users should use `modules` property in nuxt.config.js instead of `buildModules`. Causing a misunderstanding that `buildModules` property and `dev` flag should be used on nuxt versions later than v2.9 , which is wrong.

**Comment by Vissie2** [comment]
Why is this closed? The documentation isn't updated yet. 

Maybe it's common knowledge experienced Nuxt users but I could have saved me quite some time if I knew this earlier.

**Comment by ennioVisco** [comment]
> Why is this closed? The documentation isn't updated yet. Maybe it's common knowledge for experienced Nuxt users but I could have saved me quite some time if I knew this earlier.

because it is https://google-fonts.nuxtjs.org/getting-started/setup
