### ISSUE TITLE
feat: Allow use of Variable Fonts

### ISSUE THREAD

**Issue by jiblett1000** [nuxt-modules/google-fonts#133]
Thanks to the great work by @ricardogobbosouza , variable fonts are now possible using the `google-fonts-helper` in v3.3. If I'm not mistaken, I think all it would take to enable this in the module is updating that dependency (and perhaps some docs to go along with it).

**Comment by luca-smartpricing** [comment]
This code work
```js
  googleFonts: {
    preconnect: true,
    display: 'swap',
    families: {
      Inter: {
        wght: ['100..900']
      }
    }
  },
```

but not this one: 
```js
googleFonts: {
    preconnect: true,
    display: 'swap',
    families: {
      Inter: {
        wght: ['100..900'],
        slnt: ['0..-10']
      }
    }
  },
```

**Comment by jiblett1000** [comment]
@luca-smartpricing Thanks! Could you perhaps post the issue on https://github.com/datalogix/google-fonts-helper? That's where that change would need to be made. I can update this PR with the correct package version once that gets added however.

**Comment by jiblett1000** [comment]
@luca-smartpricing Do you have an example of that from the google fonts API? I'm not seeing anything here regarding slant: https://developers.google.com/fonts/docs/css2
