### ISSUE TITLE
Not all font weights are being downloaded

### ISSUE THREAD

**Issue by thijsw** [nuxt-modules/google-fonts#136]
Maybe I'm doing something wrong, but in my Nuxt project, I'm using two weights (400 and 600) of the Inter font, yet I notice that only a single weight (400) is being downloaded. Any ideas what is happening or what I might be doing wrong?

<img width="285" alt="Screenshot 2023-06-06 at 16 10 02" src="https://github.com/nuxt-modules/google-fonts/assets/28638/52a556ae-c201-42dd-aa65-87867e30a00a">

<img width="359" alt="Screenshot 2023-06-06 at 16 09 39" src="https://github.com/nuxt-modules/google-fonts/assets/28638/89152036-ce87-463c-9b49-c23eb5e3c80e">

**Comment by thijsw** [comment]
It looks like you cannot specify character subsets and font weights at the same time, when subsets are specified only the regular font weights will be downloaded

**Comment by ricardogobbosouza** [comment]
Hi @thijsw

`Subsets` existe apenas na v1 do google fonts e não existia a opção de pesos
https://developers.google.com/fonts/docs/getting_started#a_quick_example

In version 2
https://developers.google.com/fonts/docs/css2
The `subsets` option does not exist
