### ISSUE TITLE
Make it possible to set 'text' inside a font

### ISSUE THREAD

**Issue by onurusluca** [nuxt-modules/google-fonts#140]
Currently ['text'](https://google-fonts.nuxtjs.org/options#text) can only be set for all the fonts. 

It would be much better if we can set it in any font we want so that other than the general text font we have, we can have a font for a specific purpose and be it very small in size.

`before:`
```
googleFonts: {
    families: {
      Cabin: [400, 600],
      "Pathway+Gothic+One": [400]
    },
    text: "myspecifictext",
  },
```

`after:`
```
googleFonts: {
    families: {
      Cabin: [400, 600],
      "Pathway+Gothic+One": {
        wght: [400],
        text: "myspecifictext",
      },
    },
  },
```

**Comment by ricardogobbosouza** [comment]
#106
