### ISSUE TITLE
This library works for simple use cases only

### ISSUE THREAD

**Issue by episage** [nuxt-modules/google-fonts#163]
`google-fonts-helper` has a bug that prevents this library from **downloading fonts** in complex use cases such as:
```
    ['@nuxtjs/google-fonts', {
      download: true,
      text: 'AĄBCĆDEĘFGHIJKLŁMNŃOÓPRSTUWXYZŻŹaąbcćdeęfghijklłmnńoóprstuwxyzżź1234567890 `!@#$%^&*()-=_+[]{}\\|;\':",./<>?',
      families: {
        Poppins: [400, 600, 700],
      },
      preload: true,
    }],
```

I reported the bug over here https://github.com/datalogix/google-fonts-helper/issues/55

**Comment by ricardogobbosouza** [comment]
It was corrected https://github.com/datalogix/google-fonts-helper/releases/tag/v3.4.1

Tomorrow I will release a patch with fixes.

**Comment by episage** [comment]
Nice!

**Comment by ricardogobbosouza** [comment]
Fixed https://github.com/nuxt-modules/google-fonts/releases/tag/v3.1.1
