### ISSUE TITLE
Documenattion site is empty

### ISSUE THREAD

**Issue by martinjagodic** [nuxt-modules/google-fonts#185]
all resources return 404 at https://google-fonts.nuxtjs.org/

I assume this is recent and accidental as all links lead to that URL.

**Comment by geertclaes-rwe** [comment]
I was just about to submit the same issue.  I am trying to find what to do after installing @nuxtjs/google-fonts and adding  the googleFonts families to nuxt config to actually use the fonts.

**Comment by 20-buck-spin** [comment]
Same here. All requests throw 404 error (screenshot attached) 
![image](https://github.com/nuxt-modules/google-fonts/assets/96288970/a5c9422e-4016-415e-8a14-661194cb1ada)

**Comment by MaxRenglet** [comment]
@martinjagodic in the meantime, let's go back in time to get the doc !

https://web.archive.org/web/20231205093624/https://google-fonts.nuxtjs.org/getting-started/setup/

**Comment by martinjagodic** [comment]
Another way to look at the docs is the source MD files: https://github.com/nuxt-modules/google-fonts/tree/main/docs/content/1.getting-started

**Comment by geertclaes-rwe** [comment]
I thought I'd share that I stumbled on @nuxt/fonts which also covers Google Fonts

**Comment by ricardogobbosouza** [comment]
@danielroe Any idea why it's not generating the routes in netlify?

https://app.netlify.com/sites/pedantic-sinoussi-65c819/deploys/65fd8d568937b80008fb35fa
