### ISSUE TITLE
Error when deploying to Vercel

### ISSUE THREAD

**Issue by onurusluca** [nuxt-modules/google-fonts#192]
Vercel deploy failed with this error:
`[error] Error while requiring module @nuxtjs/google-fonts: Error: Cannot find module '/vercel/path0/nuxt-frontend/@nuxtjs/google-fonts'`

Local build executes without problem. I don't have any custom settings etc.

```
  modules: [
    "@nuxtjs/google-fonts", // https://google-fonts.nuxtjs.org/getting-started/setup
  ],
  googleFonts: {
    families: {
      Inter: [400, 700],
    },
  },
```

**Comment by rogerlopz** [comment]
How did you solve this @onurusluca ? Im facing the same issue but with digital ocean

**Comment by onurusluca** [comment]
@rogerlopz 
I deleted .nuxt, .output, node_modules and lock file. Reinstalled @nuxtjs/google-fonts, 
So not a solution but I am thinking I didn't install @nuxtjs/google-fonts correctly.
You can try it but I can't promise anything.

**Comment by rogerlopz** [comment]
Thank you for the response @onurusluca, I solved the issue by also reinstalling the package (my package-lock got updated). I also removed `NODE_ENV=production` from my digital ocean variables.
