### ISSUE TITLE
googleFonts families in nuxt.config

### ISSUE THREAD

**Issue by dhillweb** [nuxt-modules/google-fonts#203]
"The object literal can only specify known properties, and googleFonts does not exist in the InputConfig<NuxtConfig, ConfigLayerMeta> type."

I don't know what is the reason for this unexpected issue.

Kind regards,
Daniel

**Comment by danielhill1982** [comment]
I just use this now: https://nuxt.com/modules/fonts
It is a very nice module to quickly add webfonts like google fonts!

Thanks.
