### ISSUE TITLE
How to use it for some pege ?

### ISSUE THREAD

**Issue by golubvladimir** [nuxt-modules/google-fonts#63]
I want to use Open Sans font only on some pages. How to set it in settings ?

**Comment by samulon13** [comment]
'Open Sans' : true

**Comment by aleavikraman** [comment]
After adding `'Open+Sans': true` to your googleFonts options in nuxt.config.ts, you can then add the font as a class in your pages. 

`.some-class {
font-family: 'Open Sans', sans-serif;
}`

**Comment by danieldanielecki** [comment]
> After adding `'Open+Sans': true` to your googleFonts options in nuxt.config.ts, you can then add the font as a class in your pages.
> 
> `.some-class { font-family: 'Open Sans', sans-serif; }`

confirm, it's working (missed that in the docs, too), this issue should've been closed.

**Comment by ricardogobbosouza** [comment]
With nuxt 3 we can request stylesheets in different routes

**Comment by ricardogobbosouza** [comment]
It's still an improvement that needs to be implemented

**Comment by GnApollo** [comment]
> 'Open Sans' : true

Sorry, maybe this is not clear.

for future reference on Nuxt 2.
Here's how I do it.

**nuxt.config.js**

```
buildModules : {
....
  ['@nuxtjs/google-fonts', {
      families: {
        Roboto: true,
        'Open Sans' : true
      }
    }],
...
}
```
if you're using tailwindcss

**tailwind.config.js**
```
module.exports = {
  important: true,
  content: [
    './components/**/*.{vue,js}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './nuxt.config.{js,ts}',
  ],
  theme: {
    extend: {
      fontFamily: {
        'rob': ['Roboto'],
        'sans': ['Open Sans']
      },

    },
  }
}
```

then you can use it on your HTML as CSS.

```
<template>
    <p class="font-rob">Roboto Font</p>
    <p class="font-sans">Open Sans Font</p>
</template>

<script>
export default {}
</script>

```
