### ISSUE TITLE
Unable to turn off no-script tag in header or move it to body in nuxt

### ISSUE THREAD

**Issue by keithpowers** [nuxt-modules/google-fonts#75]
Hi i cant seem to find an option to turn off the no-script tag in the header for google fonts or move the no-script tag to the body instead could someone please give me an answer to this question as this is affecting a production site thank you

**Comment by keithpowers** [comment]
Any comments to this issue would be appreciated thank you

**Comment by ricardogobbosouza** [comment]
Hi @keithpowers 
Could you explain to me what is affecting?
So that I can provide an option for this

**Comment by keithpowers** [comment]
Hi Richard 
basically if this is in the header and not the body it causes issues with 
seo tools and also causes issues with google scoring as the no script tag 
should be in the body not the header thank you for replying it just seems 
weid that we cant have the option to remove it from the header most plugins 
have the option once again thank you for replying



-----Original Message-----
From: Ricardo Gobbo de Souza ***@***.***>
To: nuxt-community/google-fonts-module 
***@***.***>
Cc: keithpowers ***@***.***>,  Mention 
***@***.***>
Date: Wed, 30 Mar 2022 14:12:30 -0700
Subject: Re: [nuxt-community/google-fonts-module] Unable to turn off 
no-script tag in header or move it to body in nuxt (Issue #75)






Hi @keithpowers
Could you explain to me what is affecting?
So that I can provide an option for this
