### ISSUE TITLE
Is there any bug when using head method instead property?

### ISSUE THREAD

**Issue by itsmartashub** [nuxt-modules/google-fonts#84]
Hi,

Is it conceivable that changing the `head` property to the `head` method (in the `nuxt.config.js` file) causes something that "blocks" this module? I spent hours trying to figure out why _**google-fonts-module**_ didn't work for me, then I commented out the entire `head` (method) section and it began working. It also works when I use the head property instead of the head method.

Thank you in advance

**Comment by ricardogobbosouza** [comment]
Hi @itsmartashub 
This module doesn’t work when the `head` property is a `function`

In nuxt 3 the `head` property cannot be a `function`

I will create a warning in nuxt2
